{{- range .Values.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    strimzi.io/cluster: {{ .cluster }}
spec:
  {{- if .authentication }}
  authentication:
    type: {{ .authentication.type | default "scram-sha-512" }}
  {{- end }}
  {{- if and .authorization .authorization.enabled }}
  authorization:
    type: simple
    acls:
      {{- $topic := .authorization.topic | default "default-topic" }}
      {{- range .authorization.operations }}
      - resource:
          type: topic
          name: {{ $topic }}
          patternType: literal
        operation: {{ . }}
      {{- end }}
  {{- end }}
---
{{- end }}