{{- range .Values.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    strimzi.io/cluster: {{ .cluster }}
spec:
  authentication:
    type: {{ .authentication.type }}
  {{- if and .authorization.enabled .authorization.topic }}
  authorization:
    type: simple
    acls:
      {{- range .authorization.operations }}
      - resource:
          type: topic
          name: {{ $.authorization.topic }}
          patternType: literal
        operation: {{ . }}
      {{- end }}
  {{- end }}
---
{{- end }}